### ISSUE TITLE
Bertanya 

### ISSUE THREAD

**Issue by bagussatoto** [naufkia/mikpay#1]
Aplikasi yang digunakan merupakan contoh aplikasi apa ya?

Terima kasih 🙏🏽

**Comment by naufkia** [comment]
> Aplikasi yang digunakan merupakan contoh aplikasi apa ya?
> 
> Terima kasih 🙏🏽

Aplikasi seperti  ( Mikhmon > https://laksa19.github.io/ ) 
Dengan tambahan fitur lainnya, dan juga payment untuk pelanggan mini ISP
Masih blm selesai kak hehe, baru sampe payment PPP users
